### ISSUE TITLE
申请友链(范例)

### ISSUE THREAD

**Issue by tiandankanfeng** [tiandankanfeng/tiandankanfeng.github.io#1]
### 申请友链

- 网站名称（必填）: 示例
- 网站网址（必填）: https://example.com/
- 简要说明（必填）: 这是什么样的网站
- LOGO URL（必填）: https://example.com/favicon.ico
（也可以在这里上传图片）
- 标签（必填）: 编程, 生活, 创意, etc.

**Comment by flypigxyz** [comment]
网站名称：阅读·阅己
网站网址： https://theflypig.com
简要说明：逻辑只是工具，心地才是主宰！
LOGO：https://pic.flypig.xyz/pic/flypig-avatar-150.png
标签：生活，工作

**Comment by tiandankanfeng** [comment]
> 网站名称：阅读·阅己 网站网址： https://theflypig.com 简要说明：逻辑只是工具，心地才是主宰！ LOGO：https://pic.flypig.xyz/pic/flypig-avatar-150.png 标签：生活，工作

add done, https://liangye-xo.xyz/friends-links/
welcome to visit my website when idle, so as me.

**Comment by tiandankanfeng** [comment]
Halo, 我这边看到博客挂了，发生了啥事?
qq: 2252578955




恬淡看风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tiandankanfeng/Velpro.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月25日(星期天) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tiandankanfeng/Velpro.github.io] 申请友链(范例) (Issue #1)





 
网站名称：阅读·阅己
 网站网址： https://theflypig.com
 简要说明：逻辑只是工具，心地才是主宰！
 LOGO：https://pic.flypig.xyz/pic/flypig-avatar-150.png
 标签：生活，工作
